# f=open("Sample.txt","x")
f=open("Sample.txt","w")
f.write("HI EVERONE!NICE TO SEEE YOU HERE")
f.write("\nhihihrhgggghrtuh")
f.close()
f=open("Sample.txt","a")
f.write("\nhi broooooooooooooooooooooooooooooooooooooo")
f.close()
f=open("Sample.txt","r")
print(f.read())
f.close()
f=open("Sample.txt","r")
print(f.read(7))
f.close()
f=open("Sample.txt","r")
print(f.readline())
print(f.readline())
f.close()
# # f=open("del.txt","x")
# import os
# # os.remove("del.txt")
# os.rmdir()