# f=open("future.txt","x)
f=open("future.txt","w")
f.write("himwoneeeeeeeeee")
f.write("\njaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
f.close()
f=open("future.txt","a")
f.write("\nhiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii")
f.close()
f=open("future.txt","r")
f.read()
f.close()
f=open("future.txt","r")
print(f.read(7))
f.close()
f=open("future.txt","r")
print(f.readline())
print(f.readline())
f.close()
