# f=open("file1.txt","x")
# g=open("file2.txt","x")
# f=open("file1.txt","w")
# f.write("My name is kdmachaaan")
# f.close()
# f=open("file1.txt","r")
# a=f.read()
# f=open("file2.txt","w")
# f.write(a)
