# a=open("prac.txt","x")
# b=open("prac1.txt","x")
# c=open("prac2.txt","x")
a=open("prac.txt","w")
a.write("hi mwone sukalle nink")
a.close()
a=open("prac.txt","r")
d=a.read()
c=open("prac2.txt","w")
c.write(d)
b=open("prac1.txt","w")
b.write("\nhi vaaaaaaaaaaaaaaaaaaaaaave")
b.close()
b=open("prac1.txt","r")
e=b.read()
c=open("prac2.txt","a")
c.write(e)